# Generated by Django 4.0.2 on 2022-05-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_project_status_alter_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('completed', 'Complete'), ('jai', 'Just An Idea')], default='active', max_length=12, null=True),
        ),
    ]
